# Generated by Django 3.1.1 on 2020-09-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status_dipinjam',
            field=models.BooleanField(default=False),
        ),
    ]
