# Generated by Django 3.1.1 on 2020-09-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200916_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='date_back_by_member',
            field=models.DateField(blank=True, null=True),
        ),
    ]
